"""add carrier_name to shipments

Revision ID: 141799f0bb9f
Revises: 6daec3414d3c
Create Date: 2026-03-15 17:25:56.608738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141799f0bb9f'
down_revision: Union[str, Sequence[str], None] = '6daec3414d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('carrier_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'carrier_name')
    # ### end Alembic commands ###
